### ISSUE TITLE
x11 pos/pow

### ISSUE THREAD

**Issue by justinvforvendetta** [UberPay/uberpay-wallet#2]
i have a soon to be released coins electrum server up and running properly.. just had to add x11 and ntime to it.. and i did the reorg fix to the coin daemon.. its solid and hasn't crashed now since i started it two days ago..

im trying to use the bitfamily, as per dash's config.. but im getting a strange error on the android studio debug:

http://pastebin.com/K1MZ0a1q

and ideas would be great.. id like to submit a pull request when i know its working.

**Comment by justinvforvendetta** [comment]
getting this still in android debug:

11-05 18:42:29.235    1392-1457/com.coinomi.wallet.dev E/ServerClient﹕ Could not get reply for blockchain.transaction.get
    org.bitcoinj.core.ProtocolException: java.lang.ArrayIndexOutOfBoundsException: src.length=229 srcPos=217 dst.length=92 dstPos=0 length=92
            at org.bitcoinj.core.Message.readBytes(Message.java:471)
            at org.bitcoinj.core.TransactionInput.parse(TransactionInput.java:143)
            at org.bitcoinj.core.Message.<init>(Message.java:114)
            at org.bitcoinj.core.Message.<init>(Message.java:150)
            at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:52)
            at org.bitcoinj.core.TransactionInput.<init>(TransactionInput.java:126)
            at org.bitcoinj.core.Transaction.parse(Transaction.java:602)
            at org.bitcoinj.core.Message.<init>(Message.java:114)
            at org.bitcoinj.core.Message.<init>(Message.java:146)
            at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:47)
            at org.bitcoinj.core.Transaction.<init>(Transaction.java:203)
            at com.coinomi.core.network.ServerClient$10.onSuccess(ServerClient.java:444)
            at com.coinomi.core.network.ServerClient$10.onSuccess(ServerClient.java:438)
            at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
            at org.bitcoinj.utils.Threading$UserThread.run(Threading.java:107)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=229 srcPos=217 dst.length=92 dstPos=0 length=92
            at java.lang.System.arraycopy(Native Method)
            at org.bitcoinj.core.Message.readBytes(Message.java:467)
            at org.bitcoinj.core.TransactionInput.parse(TransactionInput.java:143)
            at org.bitcoinj.core.Message.<init>(Message.java:114)
            at org.bitcoinj.core.Message.<init>(Message.java:150)
            at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:52)
            at org.bitcoinj.core.TransactionInput.<init>(TransactionInput.java:126)
            at org.bitcoinj.core.Transaction.parse(Transaction.java:602)
            at org.bitcoinj.core.Message.<init>(Message.java:114)
            at org.bitcoinj.core.Message.<init>(Message.java:146)
            at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:47)
            at org.bitcoinj.core.Transaction.<init>(Transaction.java:203)
            at com.coinomi.core.network.ServerClient$10.onSuccess(ServerClient.java:444)
            at com.coinomi.core.network.ServerClient$10.onSuccess(ServerClient.java:438)
            at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
            at org.bitcoinj.utils.Threading$UserThread.run(Threading.java:107)

**Comment by justinvforvendetta** [comment]
@geopayme

**Comment by geopayme** [comment]
For which coin are you getting this error?

**Comment by justinvforvendetta** [comment]
a coin that isnt added yet, but its x11, and PoW & PoS, unlike any other coins listed, i believe. or is there a coin that fits that description in uberpay?

**Comment by geopayme** [comment]
Im a bit confused about what you try to say, can you come to http://uberpay.slack.com to chat

(finally got what you mean :dart: )

**Comment by geopayme** [comment]
try using the PeerFamily()

**Comment by justinvforvendetta** [comment]
i thought peerfamily was designed for scrypt?

**Comment by geopayme** [comment]
PPC, is a peer-to-peer cryptocurrency utilizing both proof-of-stake and proof-of-work systems

**Comment by justinvforvendetta** [comment]
scrypt algo though right? or does it work for x11 as well?

**Comment by geopayme** [comment]
it should work on x11, x13 and few other

**Comment by justinvforvendetta** [comment]
ah that was correct, ill make a pull request tonight =]
